version: '3'

services:
  load_balancer:
    build: .
    container_name: load_balancer
    ports:
      - "5000:5000"
    depends_on:
      - server1
      - server2
      - server3
      - server4  
      - server5  
      - server6  

  server1:
    build: .
    container_name: server1
    environment:
      - SERVER_ID=1

  server2:
    build: .
    container_name: server2
    environment:
      - SERVER_ID=2

  server3:
    build: .
    container_name: server3
    environment:
      - SERVER_ID=3

  server4:
    build: .
    container_name: server4
    environment:
      - SERVER_ID=4

  server5:
    build: .
    container_name: server5
    environment:
      - SERVER_ID=5

  server6:
    build: .
    container_name: server6
    environment:
      - SERVER_ID=6
