version: '3'
services:
  server1:
    build: .
    container_name: server1
    environment:
      - SERVER_ID=1
    ports:
      - "5001:5000"
  server2:
    build: .
    container_name: server2
    environment:
      - SERVER_ID=2
    ports:
      - "5002:5000"
  server3:
    build: .
    container_name: server3
    environment:
      - SERVER_ID=3
    ports:
      - "5003:5000"

